sources:
    constelations-labels:
        type: GeoJSON
        url: https://patriciogonzalezvivo.github.io/southUp/stars/sources/constellations.json
    constelations-lines:
        type: GeoJSON
        url: https://patriciogonzalezvivo.github.io/southUp/stars/sources/constellations.lines.json
    stars:
        type: GeoJSON
        url: https://patriciogonzalezvivo.github.io/southUp/stars/sources/stars.6.json