sources:
    mapzen:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=mapzen-YoRQaZF
        rasters: [normals-elevation]
        max_zoom: 16
    normals-elevation:
        type: Raster
        url: https://terrain-preview.mapzen.com/normal/{z}/{x}/{y}.png?api_key=mapzen-YoRQaZF
        max_zoom: 15
        